[package]
name = "base_station"
version = "0.1.0"
authors = ["Scott Mabin <MabezDev@gmail.com>"]
edition = "2018"

[dependencies]
smoltcp = "0.5.0"
log = "0.4.6"
env_logger = "0.6.0"
getopts = "0.2.18"
rand = "0.6.1"
url = "1.7.2"